jaffle_shop:
  outputs:
    dev:
      dataset: "{YOUR_DATASET_NAME}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: asia-northeast1
      method: oauth
      priority: interactive
      project: "{YOUR_PROJECT_ID}"
      threads: 1
      type: bigquery
  target: dev
